title: "ant0x"
description: "Blog personale e analisi CTI"
url: "https://ant0x.github.io"
baseurl: ""
repository: "ant0x/ant0x.github.io"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

theme: "minimal-mistakes-jekyll"

# Author
author:
  name: "ant0x"
  avatar: "/assets/images/avatar.png"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "ant0x"

# Navigation
header_pages:
  - index.md
  - about.md


# Minimal Mistakes options
minimal_mistakes:
  skin: "default"
  logo:
    src: "/assets/images/logo.png"

# SEO
plugins:
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - node_modules
